perfectcushion/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns =[
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.Signup.as_view(), name='signup')
]

perfectcushion/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('cart_delete/<int:product_id>', views.cart_delete, name='cart_delete'),
]

perfectcushion/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('thanks/<int:pk>/', views.SingleOrder.as_view(), name='thanks'),
    path('history/', views.OrderList.as_view(), name='order_history'),
    path('detail/<int:pk>/', views.OrderDetail.as_view(), name='order_detail'),

]

perfectcushion/perfectcushion/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('search/', include('search.urls', namespace='search')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATICFILES_DIR)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

perfectcushion/search/urls.py
from django.urls import path
from . import views

app_name='search'

urlpatterns = [
    path('', views.ProductSearch.as_view(), name='allprodcat'),
    path('product/', views.ProductSearch.as_view(), name='productsearch'),
]

perfectcushion/shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns = [
    path('', views.ListProducts.as_view(), name='allprodcat'),
    path('<slug:slug>/', views.SingleCategory.as_view(), name='productsbycategory'),
    path('product/<slug:slug>/', views.SingleProduct.as_view(), name='singleproduct'),
]

perfectcushion/templates/_footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Udemy Training. All Rights Reserved</p>
</div>

perfectcushion/templates/_header.html
{% load staticfiles %}
<header>
    <center>
        <a href="{% url 'shop:allprodcat' %}"><img src="{% static 'img/logo.png' %}" alt="Perfect Cushion Store"></a>
    </center>
</header>

perfectcushion/templates/_navbar.html
{% load bootstrap4 %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Shop
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'shop:allprodcat' %}">All Products</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            {% if item_count > 0 %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'search:productsearch' %}" method="get">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='q'>
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

perfectcushion/templates/_top-navbar.html
<div class="container">
    <div class="my_custom_menu">
        <ul>
            {% if request.user.is_authenticated %}
            <li>
                Welcome,<a href="#" class="dropdown-toggle" data-toggle='dropdown'
                        aria-haspopup='true' aria-expanded='false'>
                    {{ user.username }} <i class="fas fa-user"></i></a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a href="{% url 'order:order_history' %}" class="dropdown-item">
                        Order History
                    </a>
                </div>
            </li>
            <li>
                <a href="{% url 'accounts:logout' %}">Log Out <i class="fas fa-sign-out-alt"></i></a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'accounts:signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
            </li>
            <li>
                <a href="{% url 'accounts:login' %}">Login <i class="fas fa-sign-in-alt"></i></a>
            </li>
            {% endif %}
        </ul>


    </div>

</div>

perfectcushion/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	    <meta name="description" content="{% block metadescription %}{% endblock %}">
        <title>{% block title %} {% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <!-- Optional Theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <!-- FontAwesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'perfectcushion/css/master.css' %}">
    </head>
    <body>

        <div class="container">
            <div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
                {% include '_top-navbar.html' %}
            </div>
            {% include '_header.html' %}
            {% include '_navbar.html' %}
            {% block content %}

            {% endblock %}
        </div>
            {% include '_footer.html' %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

perfectcushion/templates/index.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock %}

{% block content %}
<h1>Test</h1>
{% endblock %}